name: Prune GHCR

on:
  workflow_call:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  prune_images:
    name: Prune old py-kube-downscaler images
    runs-on: ubuntu-latest

    steps:
      - name: Prune Images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: py-kube-downscaler
          dry-run: true
          keep-younger-than: 7 # days
          prune-untagged: true
          prune-tags-regexes: |
            ^commit-

      - name: Delete Cosign Signatures
        uses: jtaeuber/prune-orphaned-cosign-sig@v0.1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_org: ${{ github.repository_owner }}
          package_name: py-kube-downscaler
          dry-run: true
