name: Prune GHCR

on:
  workflow_call:

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  prune_images:
    name: Prune old py-kube-downscaler images
    if: github.ref != 'refs/tags/*'
    runs-on: ubuntu-latest

    steps:
      - name: Prune Images
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: py-kube-downscaler
          dry-run: true
          keep-younger-than: 7 # days
          prune-untagged: false
          prune-tags-regexes: |
            ^sha256-${{ github.sha }}\.sig$
